// This file contains the dictionary for Spanish to Zapotec translations.
let dictionary = {
    "hola": "Xhi tal xhac",
    "adiós": "cadu'yanu",
    "gracias": "Xquixepe lii",
    "por favor": "Pur favor",
    "si": "Saa'",
    "no": "Co'",
    "buenos días": "Sicaru siadó'",
    "buenas tardes": "Sicaru huadxí",
    "buenas noches": "Sicaru gueela'",
    "amor": "Guendanadxí",
    "corazón": "Ladxidó'",
    "vida": "Guenda nabani",
    "agua": "Nisa",
    "fuego": "Gui",
    "tierra": "Gidxilayú",
    "cielo": "Guiba'",
    "sol": "Gubidxa",
    "luna": "Beeu",
    "estrella": "Beleguí",
    "hombre": "Nguiu'",
    "mujer": "Gunaa'",
    "niño": "Ba'du'",
    "niña": "Ba'du'",
    "casa": "Lidxi",
    "pueblo": "Guidxi",
    "familia": "Binni lidxi",
    "amigo": "Bichi",
    "hermano": "Biche'",
    "hermana": "Bizaana",
    "padre": "Bixhoze",
    "madre": "Jñaa",
    "uno": "Tobi",
    "dos": "Chupa",
    "tres": "Chonna",
    "yo": "Naa",
    "tú": "Lii",
    "él": "Laa",
    "ella": "Laabe",
    "enserio": "Dxandí'",
    "cierto": "Dxandí'",
    "no3 temas": "cadi idxhibilu'",
    "no3 ellos digas": "cadi gudxi laacabe",
    "asi2 es2": "sicarí' nga",
    "ya caido": "ma biaba",
    "quienesx": "tuu nga",
    "elque": "ni",
    "site": "pa",
    "por yo": "pur naa",
    "todo3 el": "irá'",
    "verdad digo": "dxandí' ni cayaabe'",
    "dices2 yo": "ni ga'bu' naa",
    "lodejo": "susaana'",
    "si2 tu": "pa lii",
    "si2 dices": "pa na'lu'",
    "tellamas": "la'lu'",
    "quesea": "gacani",
    "quitatelaropa": "biré xhabalu'",
    "te amo": "nadxiee lii",
    "sanblasatempa": "Diaga beedxe'"
};
