
let translationRules = [
    // --- Phase 1: Initial Rules (from reglasuno) ---

    // type: 'twoForOne' - Replaces two consecutive words with a new phrase.
    { type: 'twoForOne', words: ['en', 'serio'], replacement: 'enserio' },
    { type: 'twoForOne', words: ['es', 'cierto'], replacement: 'cierto' },
    { type: 'twoForOne', words: ['de', 'veras'], replacement: 'cierto' },
    { type: 'twoForOne', words: ['no', 'temas'], replacement: 'no3 temas' },
    { type: 'twoForOne', words: ['es', 'veridico'], replacement: 'cierto' },

    // type: 'threeForOne' - Replaces three consecutive words with a new phrase.
    { type: 'threeForOne', words: ['no', 'les', 'digas'], replacement: 'no3 ellos digas' },

    // type: 'preprocess' - Moves a specified word to be after the word that follows it.
    { type: 'preprocess', word: 'les' },
    { type: 'preprocess', word: 'ellos' },

    { type: 'twoForOne', words: ['asi', 'es'], replacement: 'asi2 es2' },
    { type: 'twoForOne', words: ['así', 'es'], replacement: 'asi2 es2' },
    { type: 'threeForOne', words: ['asi', 'fue', 'como'], replacement: 'asi' },
    { type: 'threeForOne', words: ['así', 'fue', 'como'], replacement: 'asi' },
    { type: 'twoForOne', words: ['ha', 'caido'], replacement: 'ya caido' },
    { type: 'twoForOne', words: ['quien', 'es'], replacement: 'quienesx' },
    { type: 'twoForOne', words: ['el', 'que'], replacement: 'elque' },
    { type: 'twoForOne', words: ['si', 'te'], replacement: 'site' },
    { type: 'twoForOne', words: ['por', 'mi'], replacement: 'por yo' },
    { type: 'twoForOne', words: ['todo', 'el'], replacement: 'todo3 el' },
    { type: 'threeForOne', words: ['digo', 'la', 'verdad'], replacement: 'verdad digo' },
    { type: 'twoForOne', words: ['me', 'dices'], replacement: 'dices2 yo' },
    { type: 'twoForOne', words: ['lo', 'dejo'], replacement: 'lodejo' },
    { type: 'twoForOne', words: ['si', 'tu'], replacement: 'si2 tu' },
    { type: 'twoForOne', words: ['si', 'dices'], replacement: 'si2 dices' },

    // --- Phase 2: Main Rules (from AplicarReglasZapoteco) ---

    { type: 'twoForOne', words: ['te', 'llamas'], replacement: 'tellamas' },
    { type: 'twoForOne', words: ['buenas', 'ganancias'], replacement: 'muchas ganancias' },
    { type: 'twoForOne', words: ['que', 'sea'], replacement: 'quesea' },
    { type: 'threeForOne', words: ['quitate', 'la', 'ropa'], replacement: 'quitatelaropa' },
    { type: 'threeForOne', words: ['mi', 'dulce', 'niña'], replacement: 'niña dulce mi' },
    { type: 'twoForOne', words: ['te', 'quiero'], replacement: 'te amo' },
    { type: 'twoForOne', words: ['si', 'quieres'], replacement: 'siquieres' },
    { type: 'twoForOne', words: ['no', 'te'], replacement: 'no3' },
    { type: 'threeForOne', words: ['ya', 'está', 'despierto'], replacement: 'ya despierto' },
    { type: 'threeForOne', words: ['ya', 'esta', 'despierto'], replacement: 'ya despierto' },
    { type: 'twoForOne', words: ['estoy', 'listo'], replacement: 'estoylisto' },
    { type: 'twoForOne', words: ['todavia', 'no'], replacement: 'todaviano' },
    { type: 'twoForOne', words: ['todavía', 'no'], replacement: 'todaviano' },
    { type: 'twoForOne', words: ['aun', 'no'], replacement: 'todaviano' },
    { type: 'twoForOne', words: ['aún', 'no'], replacement: 'todaviano' },
    { type: 'twoForOne', words: ['anda', 'hablando'], replacement: 'andahablando' },
    { type: 'twoForOne', words: ['andas', 'hablando'], replacement: 'andashablando' },
    { type: 'twoForOne', words: ['la', 'veía'], replacement: 'veía la2' },
    { type: 'twoForOne', words: ['lo', 'veía'], replacement: 'veía la2' },
    { type: 'threeForOne', words: ['en', 'aquel', 'tiempo'], replacement: 'aqueltiempo' },
    { type: 'twoForOne', words: ['aquel', 'tiempo'], replacement: 'aqueltiempo' },
    { type: 'threeForOne', words: ['en', 'donde', 'está'], replacement: 'endonde' },
    { type: 'threeForOne', words: ['en', 'donde', 'esta'], replacement: 'endonde' },
    { type: 'twoForOne', words: ['el', 'arbol'], replacement: 'elarbol' },
    { type: 'twoForOne', words: ['el', 'árbol'], replacement: 'elarbol' },
    { type: 'twoForOne', words: ['en', 'dónde'], replacement: 'donde2' },
    { type: 'twoForOne', words: ['en', 'donde'], replacement: 'endonde' },
    { type: 'twoForOne', words: ['por', 'aqui'], replacement: 'poraqui' },
    { type: 'twoForOne', words: ['por', 'aquí'], replacement: 'poraqui' },
    { type: 'twoForOne', words: ['mi', 'espalda'], replacement: 'miespalda' },
    { type: 'twoForOne', words: ['se', 'acabó'], replacement: 'ya acabó2' },
    { type: 'threeForOne', words: ['a', 'la', 'casa'], replacement: 'a casa2' },
    { type: 'twoForOne', words: ['me', 'encanta'], replacement: 'encanta' },
    { type: 'twoForOne', words: ['tu', 'padre'], replacement: 'tupadre' },
    { type: 'twoForOne', words: ['aire', 'que'], replacement: 'aire que2' },
    { type: 'threeForOne', words: ['todo', 'en', 'zapoteco'], replacement: 'todo2 zapoteco' },
    { type: 'threeForOne', words: ['ya', 'no', 'tengo'], replacement: 'ya no2 tengo2' },
    { type: 'twoForOne', words: ['quiero', 'ir'], replacement: 'quiero ir3' },
    { type: 'twoForOne', words: ['estamos', 'viendo'], replacement: 'estamosviendo' },
    { type: 'twoForOne', words: ['puedo', 'ir'], replacement: 'puedo ir3' },
    { type: 'twoForOne', words: ['tengo', 'que'], replacement: 'tengo que4' },
    { type: 'twoForOne', words: ['tengo', 'sueño'], replacement: 'tengosueño' },
    { type: 'twoForOne', words: ['tengo', 'miedo'], replacement: 'tengomiedo' },

    // type: 'ifAtStart' - Replaces a word only if it's the first word of the text.
    { type: 'ifAtStart', word: 'oye', replacement: 'oye2' },

    { type: 'twoForOne', words: ['hijo', 'mio'], replacement: 'hijo' },
    { type: 'twoForOne', words: ['hijo', 'mío'], replacement: 'hijo' },
    { type: 'twoForOne', words: ['la', 'ventosa'], replacement: 'laventosa' },
    { type: 'twoForOne', words: ['salina', 'cruz'], replacement: 'salinacruz' },
    { type: 'twoForOne', words: ['el', 'espinal'], replacement: 'elespinal' },
    { type: 'twoForOne', words: ['no', 'quieras'], replacement: 'no3 quieras' },
    { type: 'twoForOne', words: ['un', 'solo'], replacement: 'unsolo' },
    { type: 'twoForOne', words: ['la', 'ropa'], replacement: 'laropa' },
    { type: 'twoForOne', words: ['no', 'me'], replacement: 'no3 me' },
    { type: 'twoForOne', words: ['en', 'uno'], replacement: 'uno' },
    { type: 'twoForOne', words: ['en', 'dos'], replacement: 'dos' },
    { type: 'twoForOne', words: ['que', 'te'], replacement: 'te' },
    { type: 'twoForOne', words: ['en', 'tres'], replacement: 'tres' },
    { type: 'twoForOne', words: ['en', 'cuatro'], replacement: 'cuatro' },
    { type: 'twoForOne', words: ['en', 'cinco'], replacement: 'cinco' },
    { type: 'twoForOne', words: ['en', 'seis'], replacement: 'seis' },
    { type: 'twoForOne', words: ['en', 'siete'], replacement: 'siete' },
    { type: 'twoForOne', words: ['en', 'ocho'], replacement: 'ocho' },
    { type: 'twoForOne', words: ['en', 'nueve'], replacement: 'nueve' },
    { type: 'twoForOne', words: ['en', 'diez'], replacement: 'diez' },
    { type: 'twoForOne', words: ['en', '1'], replacement: 'uno' },
    { type: 'twoForOne', words: ['en', '2'], replacement: 'dos' },
    { type: 'twoForOne', words: ['en', '3'], replacement: 'tres' },
    { type: 'twoForOne', words: ['en', '4'], replacement: 'cuatro' },
    { type: 'twoForOne', words: ['en', '5'], replacement: 'cinco' },
    { type: 'twoForOne', words: ['en', '6'], replacement: 'seis' },
    { type: 'twoForOne', words: ['en', '7'], replacement: 'siete' },
    { type: 'twoForOne', words: ['en', '8'], replacement: 'ocho' },
    { type: 'twoForOne', words: ['en', '9'], replacement: 'nueve' },
    { type: 'twoForOne', words: ['en', '10'], replacement: 'diez' },
    { type: 'twoForOne', words: ['un', 'partes'], replacement: 'un pedazo' },
    { type: 'twoForOne', words: ['dos', 'partes'], replacement: 'dos pedazo' },
    { type: 'twoForOne', words: ['tres', 'partes'], replacement: 'tres pedazo' },
    { type: 'twoForOne', words: ['cuatro', 'partes'], replacement: 'cuatro pedazo' },
    { type: 'twoForOne', words: ['cinco', 'partes'], replacement: 'cinco pedazo' },
    { type: 'twoForOne', words: ['seis', 'partes'], replacement: 'seis pedazo' },
    { type: 'twoForOne', words: ['siete', 'partes'], replacement: 'siete pedazo' },
    { type: 'twoForOne', words: ['ocho', 'partes'], replacement: 'ocho pedazo' },
    { type: 'twoForOne', words: ['nueve', 'partes'], replacement: 'nueve pedazo' },
    { type: 'twoForOne', words: ['diez', 'partes'], replacement: 'diez pedazo' },
    { type: 'twoForOne', words: ['1', 'partes'], replacement: 'un pedazo' },
    { type: 'twoForOne', words: ['2', 'partes'], replacement: 'dos pedazo' },
    { type: 'twoForOne', words: ['3', 'partes'], replacement: 'tres pedazo' },
    { type: 'twoForOne', words: ['4', 'partes'], replacement: 'cuatro pedazo' },
    { type: 'twoForOne', words: ['5', 'partes'], replacement: 'cinco pedazo' },
    { type: 'twoForOne', words: ['6', 'partes'], replacement: 'seis pedazo' },
    { type: 'twoForOne', words: ['7', 'partes'], replacement: 'siete pedazo' },
    { type: 'twoForOne', words: ['8', 'partes'], replacement: 'ocho pedazo' },
    { type: 'twoForOne', words: ['9', 'partes'], replacement: 'nueve pedazo' },
    { type: 'twoForOne', words: ['10', 'partes'], replacement: 'diez pedazo' },
    { type: 'threeForOne', words: ['no', 'estoy', 'asustado'], replacement: 'no3 asustado2' },
    { type: 'threeForOne', words: ['pan', 'de', 'muerto'], replacement: 'pandemuerto' },
    { type: 'twoForOne', words: ['solo', 'un'], replacement: 'unsolo' },
    { type: 'twoForOne', words: ['tierra', 'blanca'], replacement: 'tierrablanca' },
    { type: 'twoForOne', words: ['lo', 'que'], replacement: 'eso2' },
    { type: 'twoForOne', words: ['lo', 'he'], replacement: '' },
    { type: 'threeForOne', words: ['lo', 'que', 'dice'], replacement: 'eso2 dice2' },

    // type: 'fourForOne' - Replaces four consecutive words with a new phrase.
    { type: 'fourForOne', words: ['lo', 'que', 'está', 'escrito'], replacement: 'eso2 dice2 papel' },
    { type: 'fourForOne', words: ['lo', 'que', 'esta', 'escrito'], replacement: 'eso2 dice2 papel' },

    { type: 'twoForOne', words: ['haré', 'todo'], replacement: 'haré todo3' },
    { type: 'twoForOne', words: ['hare', 'todo'], replacement: 'haré todo3' },
    { type: 'twoForOne', words: ['cada', 'uno'], replacement: 'cada2 uno' },
    { type: 'threeForOne', words: ['san', 'blas', 'atempa'], replacement: 'sanblasatempa' },
    { type: 'threeForOne', words: ['mata', 'de', 'platano'], replacement: 'matadeplatano' },
    { type: 'threeForOne', words: ['racimo', 'de', 'platano'], replacement: 'racimo platano' },
    { type: 'fourForOne', words: ['no', 'nos', 'hemos', 'ido'], replacement: 'no4 hemosido' },
    { type: 'twoForOne', words: ['un', 'chingo'], replacement: 'unchingo' },
    { type: 'threeForOne', words: ['en', 'todo', 'momento'], replacement: 'todo dia' },
    { type: 'twoForOne', words: ['es', 'necesario'], replacement: 'necesario' },
    { type: 'twoForOne', words: ['en', 'mi'], replacement: 'en2' },
    { type: 'twoForOne', words: ['platano', 'macho'], replacement: 'platano macho2' },
    { type: 'twoForOne', words: ['agua', 'caliente'], replacement: 'agua caliente2' },
    { type: 'twoForOne', words: ['monte', 'grande'], replacement: 'montegrande' },
    { type: 'twoForOne', words: ['unión', 'hidalgo'], replacement: 'unionhidalgo' },
    { type: 'twoForOne', words: ['union', 'hidalgo'], replacement: 'unionhidalgo' },
    { type: 'twoForOne', words: ['tiene', 'miedo'], replacement: 'tienemiedo' },
    { type: 'twoForOne', words: ['está', 'asustado'], replacement: 'tienemiedo' },
    { type: 'twoForOne', words: ['esta', 'asustado'], replacement: 'tienemiedo' },
    { type: 'twoForOne', words: ['ir', 'con'], replacement: 'ir3 con' },
    { type: 'fourForOne', words: ['de', 'ir', 'a', 'la'], replacement: 'de2 ir2' },
    { type: 'threeForOne', words: ['conforme', 'al', 'corazón'], replacement: 'conforme corazón' },
    { type: 'threeForOne', words: ['conforme', 'al', 'corazon'], replacement: 'conforme corazón' },
    { type: 'threeForOne', words: ['nunca', 'te', 'olvides'], replacement: 'nunca olvides' },
    { type: 'twoForOne', words: ['es', 'mejor'], replacement: 'más hermoso' },
    { type: 'twoForOne', words: ['es', 'bueno'], replacement: 'más hermoso' },
    { type: 'twoForOne', words: ['seamos', 'amigos'], replacement: 'seamos amigos2' },
    { type: 'twoForOne', words: ['otra', 'vez'], replacement: 'otro2 vez' },
    { type: 'twoForOne', words: ['se', 'baña'], replacement: 'sebaña' },
    { type: 'twoForOne', words: ['un', 'poco'], replacement: 'unpoco' },
    { type: 'threeForOne', words: ['dar', 'para', 'recibir'], replacement: 'dar para2 recibir' },
    { type: 'threeForOne', words: ['mira', 'nada', 'más'], replacement: 'mira2 veas' },
    { type: 'threeForOne', words: ['por', 'sus', 'hijos'], replacement: 'por sus hijos2' },
    { type: 'threeForOne', words: ['como', 'le', 'decía'], replacement: 'como2 le decía' },
    { type: 'threeForOne', words: ['como', 'te', 'decía'], replacement: 'como2 te decía' },
    { type: 'twoForOne', words: ['como', 'esas'], replacement: 'como2 esas2' },
    { type: 'twoForOne', words: ['de', 'oro'], replacement: 'oro' },
    { type: 'twoForOne', words: ['se', 'ríe'], replacement: 'ríendo' },
    { type: 'twoForOne', words: ['se', 'vea'], replacement: 'sevea' },
    { type: 'twoForOne', words: ['se', 'llama'], replacement: 'sellama' },
    { type: 'threeForOne', words: ['te', 'estoy', 'viendo'], replacement: 'viendo te' },
    { type: 'twoForOne', words: ['te', 'ríes'], replacement: 'teríes' },
    { type: 'twoForOne', words: ['te', 'ries'], replacement: 'teríes' },
    { type: 'twoForOne', words: ['me', 'rio'], replacement: 'merio' },
    { type: 'twoForOne', words: ['me', 'río'], replacement: 'merio' },
    { type: 'twoForOne', words: ['de', 'ti'], replacement: 'de2 ti' },
    { type: 'twoForOne', words: ['sus', 'hijos'], replacement: 'sus hijos2' },
    { type: 'twoForOne', words: ['sus', 'hijas'], replacement: 'sus hijos2' },
    { type: 'twoForOne', words: ['son', 'más'], replacement: 'hay más' },
    { type: 'twoForOne', words: ['yo', 'soy'], replacement: 'yosoy' },
    { type: 'twoForOne', words: ['lo', 'da'], replacement: 'da2' },
    { type: 'twoForOne', words: ['da', 'todo'], replacement: 'da2 todo' },
    { type: 'twoForOne', words: ['somos', 'más'], replacement: 'somos más2' },
    { type: 'twoForOne', words: ['a', 'ver'], replacement: 'ver' },
    { type: 'twoForOne', words: ['los', 'buenos'], replacement: 'los gente buenos2' },
    { type: 'threeForOne', words: ['a', 'mi', 'mamá'], replacement: 'mi mamá' },
    { type: 'threeForOne', words: ['en', 'este', 'momento'], replacement: 'ahorita' },
    { type: 'threeForOne', words: ['a', 'mi', 'papá'], replacement: 'mi papá' },
    { type: 'threeForOne', words: ['día', 'de', 'muertos'], replacement: 'diademuertos' },
    { type: 'threeForOne', words: ['dia', 'de', 'muertos'], replacement: 'diademuertos' },
    { type: 'threeForOne', words: ['a', 'mi', 'abuelo'], replacement: 'mi abuelo' },
    { type: 'threeForOne', words: ['a', 'mi', 'abuela'], replacement: 'mi abuela' },
    { type: 'threeForOne', words: ['a', 'mi', 'hermano'], replacement: 'mi hermano' },
    { type: 'threeForOne', words: ['a', 'mi', 'hermana'], replacement: 'mi hermana' },
    { type: 'threeForOne', words: ['vamos', 'a', 'ser'], replacement: 'seamos' },
    { type: 'threeForOne', words: ['va', 'a', 'hacer'], replacement: 'vaahacer' },
    { type: 'twoForOne', words: ['está', 'haciendo'], replacement: 'estahaciendo' },
    { type: 'twoForOne', words: ['esta', 'haciendo'], replacement: 'estahaciendo' },
    { type: 'threeForOne', words: ['esta', 'haciendo', 'frio'], replacement: 'estahaciendo frio2' },
    { type: 'threeForOne', words: ['está', 'haciendo', 'frío'], replacement: 'estahaciendo frio2' },
    { type: 'twoForOne', words: ['tiene', 'frio'], replacement: 'tiene2 frio2' },
    { type: 'threeForOne', words: ['está', 'haciendo', 'calor'], replacement: 'estahaciendo calor2' },
    { type: 'threeForOne', words: ['lo', 'vi', 'ayer'], replacement: 'ayer vi2' },
    { type: 'threeForOne', words: ['que', 'los', 'malos'], replacement: 'que3 los gente malos' },
    { type: 'twoForOne', words: ['los', 'malos'], replacement: 'gente malos' },
    { type: 'threeForOne', words: ['soy', 'el', 'ingeniero'], replacement: 'yo soy2 ingeniero' },
    { type: 'fourForOne', words: ['yo', 'soy', 'el', 'ingeniero'], replacement: 'yo soy2 ingeniero' },
    { type: 'threeForOne', words: ['soy', 'el', 'licenciado'], replacement: 'yo soy2 licenciado' },
    { type: 'fourForOne', words: ['yo', 'soy', 'el', 'licenciado'], replacement: 'yo soy2 licenciado' },
    { type: 'fourForOne', words: ['te', 'acuerdas', 'de', 'mi'], replacement: 'teacuerdas yo' },
    { type: 'twoForOne', words: ['te', 'llamé'], replacement: 'tellamé' },
    { type: 'twoForOne', words: ['una', 'cosa'], replacement: 'cosa' },
    { type: 'twoForOne', words: ['ustedes', 'tienen'], replacement: 'ustedes tienen2' },
    { type: 'threeForOne', words: ['vengo', 'a', 'comprar'], replacement: 'vengo acomprar' },
    { type: 'threeForOne', words: ['vine', 'a', 'comprar'], replacement: 'vengo acomprar' },
    { type: 'twoForOne', words: ['vengo', 'a'], replacement: 'vengo' },
    { type: 'twoForOne', words: ['a', 'esa'], replacement: 'esa' },

    { type: 'preprocess', word: 'esa' },
    { type: 'preprocess', word: 'te' },

    { type: 'threeForOne', words: ['puedo', 'te', 'decir'], replacement: 'puedo decir te' },
    { type: 'threeForOne', words: ['todo', 'está', 'bien'], replacement: 'todo2 está2 bien2' },
    { type: 'twoForOne', words: ['tus', 'ojos'], replacement: 'tusojos' },
    { type: 'twoForOne', words: ['tu', 'casa'], replacement: 'tucasa' },
    { type: 'twoForOne', words: ['tu', 'obligación'], replacement: 'tuobligación' },
    { type: 'twoForOne', words: ['tu', 'obligacion'], replacement: 'tuobligación' },
    { type: 'twoForOne', words: ['tu', 'sonrisa'], replacement: 'tusonrisa' },
    { type: 'twoForOne', words: ['tu', 'risa'], replacement: 'tusonrisa' },
    { type: 'twoForOne', words: ['estamos', 'vivos'], replacement: 'vivos' },

    { type: 'preprocess', word: 'tus' },

    { type: 'twoForOne', words: ['mi', 'mano'], replacement: 'mimano' },
    { type: 'twoForOne', words: ['tu', 'mano'], replacement: 'tumano' },
    { type: 'twoForOne', words: ['tu', 'frente'], replacement: 'tufrente' },
    { type: 'twoForOne', words: ['mi', 'frente'], replacement: 'mifrente' },
    { type: 'twoForOne', words: ['mi', 'casa'], replacement: 'micasa' },
    { type: 'twoForOne', words: ['mi', 'corazón'], replacement: 'micorazón' },
    { type: 'twoForOne', words: ['mi', 'corazon'], replacement: 'micorazón' },
    { type: 'twoForOne', words: ['mi', 'pie'], replacement: 'mipie' },
    { type: 'twoForOne', words: ['mi', 'brazo'], replacement: 'mibrazo' },
    { type: 'twoForOne', words: ['mi', 'cabeza'], replacement: 'micabeza' },
    { type: 'twoForOne', words: ['mis', 'ojos'], replacement: 'misojos' },
    { type: 'twoForOne', words: ['mi', 'ojo'], replacement: 'miojo' },
    { type: 'twoForOne', words: ['mi', 'nariz'], replacement: 'minariz' },
    { type: 'twoForOne', words: ['mis', 'pestañas'], replacement: 'mispestañas' },
    { type: 'twoForOne', words: ['mi', 'rodilla'], replacement: 'mirodilla' },
    { type: 'twoForOne', words: ['mi', 'oreja'], replacement: 'mioreja' },
    { type: 'twoForOne', words: ['mi', 'oido'], replacement: 'mioido' },
    { type: 'twoForOne', words: ['mis', 'orejas'], replacement: 'misorejas' },
    { type: 'twoForOne', words: ['mis', 'oidos'], replacement: 'misoidos' },
    { type: 'twoForOne', words: ['mi', 'esposa'], replacement: 'esposa' },
    { type: 'twoForOne', words: ['mi', 'esposo'], replacement: 'esposo' },
    { type: 'twoForOne', words: ['mi', 'hijo'], replacement: 'mihijo' },
    { type: 'twoForOne', words: ['de', 'mí'], replacement: 'mi2' },

    { type: 'preprocess', word: 'mi' },
    { type: 'preprocess', word: 'mis' },
    { type: 'preprocess', word: 'su' },
    { type: 'preprocess', word: 'nuestro' },
    { type: 'preprocess', word: 'nuestra' },
    { type: 'preprocess', word: 'esos' },
    { type: 'preprocess', word: 'este' },

    { type: 'twoForOne', words: ['es', 'este'], replacement: 'este es2' },
    
    { type: 'preprocess', word: 'esta' },
    { type: 'preprocess', word: 'ése' },
    { type: 'preprocess', word: 'ese' },
    { type: 'preprocess', word: 'le' },
    { type: 'preprocess', word: 'aquel' },

    { type: 'twoForOne', words: ['no', 'hay'], replacement: 'nohay' },
    { type: 'twoForOne', words: ['estoy', 'vivo'], replacement: 'vivo' },
    { type: 'twoForOne', words: ['no', 'es'], replacement: 'noes' },
    { type: 'threeForOne', words: ['no', 'está', 'bien'], replacement: 'no3 bien2 eso' },
    { type: 'threeForOne', words: ['no', 'te', 'entendí'], replacement: 'no2 te entendí' },
    { type: 'threeForOne', words: ['no', 'te', 'entendo'], replacement: 'no3 te entendo' },
    
    // type: 'replaceWord' - Replaces all instances of a specific word.
    { type: 'replaceWord', word: 'no', replacement: 'no2' },
    
    { type: 'twoForOne', words: ['no2', 'estás'], replacement: 'no2 estás2' },
    { type: 'twoForOne', words: ['no2', 'estabas'], replacement: 'no2 estabas2' },
    { type: 'threeForOne', words: ['toda', 'la', 'noche'], replacement: 'todalanoche' },
    { type: 'threeForOne', words: ['toda', 'la', 'madrugada'], replacement: 'todalanoche' },
    
    // type: 'replaceIfNext' - Replaces a word with its replacement only if it's followed by a specific word.
    // Format: { type: 'replaceIfNext', word: 'wordToReplace', next: 'wordThatMustFollow', replacement: 'newWord' }
    { type: 'replaceIfNext', word: 'otro', next: 'camino', replacement: 'otro2' },
    { type: 'replaceIfNext', word: 'come', next: 'caca', replacement: 'come2' },
    { type: 'replaceIfNext', word: 'come', next: 'mierda', replacement: 'come2' },
    
    // type: 'replaceIfPrevious' - Replaces a word with its replacement only if it's preceded by a specific word.
    // Format: { type: 'replaceIfPrevious', word: 'wordToReplace', previous: 'wordThatMustPrecede', replacement: 'newWord' }
    { type: 'replaceIfPrevious', word: 'quisiera', previous: 'el', replacement: 'quisiera2' },
    { type: 'replaceIfPrevious', word: 'quisiera', previous: 'ella', replacement: 'quisiera2' },

    { type: 'replaceIfNext', word: 'no2', next: 'eres', replacement: 'no3' },

    { type: 'replaceIfPrevious', word: 'mi', previous: 'para', replacement: 'mi2' },
    { type: 'replaceIfNext', word: 'para', next: 'mi2', replacement: 'para2' },
    { type: 'replaceIfNext', word: 'la', next: 'encontré', replacement: 'la2' },
    { type: 'replaceIfNext', word: 'lo', next: 'encontré', replacement: 'la2' },
    { type: 'replaceIfNext', word: 'le', next: 'encontré', replacement: 'la2' },

    { type: 'preprocess', word: 'la2' },

    { type: 'replaceIfNext', word: 'tu', next: 'amor', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'camino', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'sendero', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'sueño', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'vida', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'escuela', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'trabajo', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'arbol', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'árbol', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'cabeza', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'pie', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'boca', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'mano', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'mamá', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'mama', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'papa', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'alma', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'perro', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'gato', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'cara', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'corazón', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'corazon', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'voz', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'amigo', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'amiga', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'hermano', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'hermana', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'primo', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'prima', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'pelo', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'oreja', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'labio', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'rodilla', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'hombligo', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'costilla', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'estomago', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'cintura', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'arma', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'rancho', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'terreno', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'novio', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'novia', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'esposo', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'esposa', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'amante', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'hijo', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'hija', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'tía', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'tia', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'tío', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'tio', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'abuelo', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'abuela', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'sobrino', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'muerte', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'carro', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'carreta', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'bicicleta', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'ganado', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'cerveza', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'tlayuda', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'refresco', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'boda', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'familia', replacement: 'tu2' },
    { type: 'replaceIfNext', word: 'tu', next: 'culpa', replacement: 'tu2' },

    { type: 'preprocess', word: 'tu2' },

    { type: 'twoForOne', words: ['tu', 'eres'], replacement: 'tu eres2' },
    { type: 'threeForOne', words: ['tu', 'eres', 'el'], replacement: 'tu eres2' },
    { type: 'twoForOne', words: ['me', 'vendió'], replacement: 'vendió' },
    { type: 'twoForOne', words: ['me', 'pica'], replacement: 'pica' },
    { type: 'twoForOne', words: ['me', 'compró'], replacement: 'compró2 para2 yo' },
    { type: 'fourForOne', words: ['me', 'ha', 'enseñado', 'todo'], replacement: 'me enseñado todo2' },
    { type: 'twoForOne', words: ['me', 'enseñaste'], replacement: 'me enseñaste2' },
    { type: 'threeForOne', words: ['me', 'hizo', 'pedazos'], replacement: 'me hizo dos pedazos' },
    { type: 'threeForOne', words: ['me', 'siento', 'mejor'], replacement: 'estoy correcto' },

    { type: 'preprocess', word: 'me' },
    
    { type: 'replaceIfNext', word: 'como', next: 'una', replacement: 'como2' },
    { type: 'replaceIfNext', word: 'como', next: 'un', replacement: 'como2' },
    
    // type: 'remove' - Removes all instances of a specific word.
    { type: 'remove', word: 'el' },
    { type: 'remove', word: 'la' },
    
    { type: 'replaceIfNext', word: 'a', next: 'veces', replacement: 'a2' },

    { type: 'twoForOne', words: ['quisiste', 'ser'], replacement: 'quisisteser' },
    { type: 'twoForOne', words: ['por', 'qué'], replacement: 'porque2' },
    { type: 'twoForOne', words: ['para', 'qué'], replacement: 'porque2' },
    { type: 'twoForOne', words: ['para', 'que'], replacement: 'para2' },
    { type: 'twoForOne', words: ['de', 'noche'], replacement: 'denoche' },
    { type: 'twoForOne', words: ['ella', 'tiene'], replacement: 'ellatiene' },
    { type: 'twoForOne', words: ['él', 'tiene'], replacement: 'ellatiene' },
    { type: 'twoForOne', words: ['otro', 'año'], replacement: 'otroaño' },
    { type: 'twoForOne', words: ['anda', 'jugando'], replacement: 'andajugando' },
    { type: 'twoForOne', words: ['está', 'jugando'], replacement: 'andajugando' },
    { type: 'twoForOne', words: ['ha', 'llegado'], replacement: 'llegado' },

    { type: 'ifAtStart', word: 'para', replacement: 'para2' },
    
    { type: 'twoForOne', words: ['ya', 'ha'], replacement: 'ya' },
    { type: 'twoForOne', words: ['hay', 'que'], replacement: 'tengoque' },

    // type: 'fiveForOne' - Replaces five consecutive words with a new phrase.
    { type: 'fiveForOne', words: ['no2', 'le', 'tengas', 'miedo', 'al'], replacement: 'no3 tengasmiedo' },

    { type: 'fourForOne', words: ['no2', 'le', 'tengas', 'miedo'], replacement: 'no3 tengasmiedo el' },
    { type: 'twoForOne', words: ['el', 'pueblo'], replacement: 'gente pueblo' },
    { type: 'twoForOne', words: ['del', 'pueblo'], replacement: 'del gente pueblo' },
    { type: 'threeForOne', words: ['no2', 'tengas', 'miedo'], replacement: 'no3 tengasmiedo' },
];
